# -*- coding: utf-8 -*-
"""blue print
"""
from vmf.properties.views import bp_properties
from vmf.group.views import bp_group
from vmf.user.views import bp_user
from vmf.group.forms import GroupCreateForm


def register_bp(app_):
    """register bp
    """
    app_.register_blueprint(bp_properties)
    #
    app_.register_blueprint(bp_group)
    #
    app_.register_blueprint(bp_user)


urls = {'/vmf/properties/index': '',
        '/vmf/properties/create': '',
        '/vmf/properties/detail': '',
        '/vmf/properties/modify': '',
        '/vmf/properties/delete': '',
        '/vmf/properties/index-get': '',
        '/vmf/properties/create-get': '',
        '/vmf/properties/detail-get': '',
        '/vmf/properties/modify-get': '',
        '/vmf/properties/delete-get': '',

        '/vmf/user/index': '',
        '/vmf/user/create': '',
        '/vmf/user/detail': '',
        '/vmf/user/modify': '',
        '/vmf/user/delete': '',
        '/vmf/user/index-get': '',
        '/vmf/user/create-get': '',
        '/vmf/user/detail-get': '',
        '/vmf/user/modify-get': '',
        '/vmf/user/delete-get': '',
        '/vmf/user/index-post': '',
        '/vmf/user/create-post': '',
        '/vmf/user/detail-post': '',
        '/vmf/user/modify-post': '',
        '/vmf/user/delete-post': '',

        '/vmf/group/index': '',
        '/vmf/group/create': '',
        '/vmf/group/detail': '',
        '/vmf/group/modify': '',
        '/vmf/group/delete': '',
        '/vmf/group/index-get': '',
        '/vmf/group/create-get': '',
        '/vmf/group/detail-get': '',
        '/vmf/group/modify-get': '',
        '/vmf/group/delete-get': '',
        '/vmf/group/index-post': '',
        '/vmf/group/create-post': GroupCreateForm,
        '/vmf/group/detail-post': '',
        '/vmf/group/modify-post': '',
        '/vmf/group/delete-post': '',

        '/vmf/m0/index': '',
        '/vmf/m0/create': '',
        '/vmf/m0/detail': '',
        '/vmf/m0/modify': '',
        '/vmf/m0/delete': '',
        '/vmf/m0/index-get': '',
        '/vmf/m0/create-get': '',
        '/vmf/m0/detail-get': '',
        '/vmf/m0/modify-get': '',
        '/vmf/m0/delete-get': '',
        '/vmf/m0/index-post': '',
        '/vmf/m0/create-post': GroupCreateForm,
        '/vmf/m0/detail-post': '',
        '/vmf/m0/modify-post': '',
        '/vmf/m0/delete-post': '',

        '/vmf/m1/index': '',
        '/vmf/m1/create': '',
        '/vmf/m1/detail': '',
        '/vmf/m1/modify': '',
        '/vmf/m1/delete': '',
        '/vmf/m1/index-get': '',
        '/vmf/m1/create-get': '',
        '/vmf/m1/detail-get': '',
        '/vmf/m1/modify-get': '',
        '/vmf/m1/delete-get': '',
        '/vmf/m1/index-post': '',
        '/vmf/m1/create-post': GroupCreateForm,
        '/vmf/m1/detail-post': '',
        '/vmf/m1/modify-post': '',
        '/vmf/m1/delete-post': '',

        '/vmf/m2/index': '',
        '/vmf/m2/create': '',
        '/vmf/m2/detail': '',
        '/vmf/m2/modify': '',
        '/vmf/m2/delete': '',
        '/vmf/m2/index-get': '',
        '/vmf/m2/create-get': '',
        '/vmf/m2/detail-get': '',
        '/vmf/m2/modify-get': '',
        '/vmf/m2/delete-get': '',
        '/vmf/m2/index-post': '',
        '/vmf/m2/create-post': GroupCreateForm,
        '/vmf/m2/detail-post': '',
        '/vmf/m2/modify-post': '',
        '/vmf/m2/delete-post': '',

        '/vmf/m3/index': '',
        '/vmf/m3/create': '',
        '/vmf/m3/detail': '',
        '/vmf/m3/modify': '',
        '/vmf/m3/delete': '',
        '/vmf/m3/index-get': '',
        '/vmf/m3/create-get': '',
        '/vmf/m3/detail-get': '',
        '/vmf/m3/modify-get': '',
        '/vmf/m3/delete-get': '',
        '/vmf/m3/index-post': '',
        '/vmf/m3/create-post': GroupCreateForm,
        '/vmf/m3/detail-post': '',
        '/vmf/m3/modify-post': '',
        '/vmf/m3/delete-post': '',

        '/vmf/m4/index': '',
        '/vmf/m4/create': '',
        '/vmf/m4/detail': '',
        '/vmf/m4/modify': '',
        '/vmf/m4/delete': '',
        '/vmf/m4/index-get': '',
        '/vmf/m4/create-get': '',
        '/vmf/m4/detail-get': '',
        '/vmf/m4/modify-get': '',
        '/vmf/m4/delete-get': '',
        '/vmf/m4/index-post': '',
        '/vmf/m4/create-post': GroupCreateForm,
        '/vmf/m4/detail-post': '',
        '/vmf/m4/modify-post': '',
        '/vmf/m4/delete-post': '',

        '/vmf/m5/index': '',
        '/vmf/m5/create': '',
        '/vmf/m5/detail': '',
        '/vmf/m5/modify': '',
        '/vmf/m5/delete': '',
        '/vmf/m5/index-get': '',
        '/vmf/m5/create-get': '',
        '/vmf/m5/detail-get': '',
        '/vmf/m5/modify-get': '',
        '/vmf/m5/delete-get': '',
        '/vmf/m5/index-post': '',
        '/vmf/m5/create-post': GroupCreateForm,
        '/vmf/m5/detail-post': '',
        '/vmf/m5/modify-post': '',
        '/vmf/m5/delete-post': '',

        '/vmf/m6/index': '',
        '/vmf/m6/create': '',
        '/vmf/m6/detail': '',
        '/vmf/m6/modify': '',
        '/vmf/m6/delete': '',
        '/vmf/m6/index-get': '',
        '/vmf/m6/create-get': '',
        '/vmf/m6/detail-get': '',
        '/vmf/m6/modify-get': '',
        '/vmf/m6/delete-get': '',
        '/vmf/m6/index-post': '',
        '/vmf/m6/create-post': GroupCreateForm,
        '/vmf/m6/detail-post': '',
        '/vmf/m6/modify-post': '',
        '/vmf/m6/delete-post': '',

        '/vmf/m7/index': '',
        '/vmf/m7/create': '',
        '/vmf/m7/detail': '',
        '/vmf/m7/modify': '',
        '/vmf/m7/delete': '',
        '/vmf/m7/index-get': '',
        '/vmf/m7/create-get': '',
        '/vmf/m7/detail-get': '',
        '/vmf/m7/modify-get': '',
        '/vmf/m7/delete-get': '',
        '/vmf/m7/index-post': '',
        '/vmf/m7/create-post': GroupCreateForm,
        '/vmf/m7/detail-post': '',
        '/vmf/m7/modify-post': '',
        '/vmf/m7/delete-post': '',

        '/vmf/m8/index': '',
        '/vmf/m8/create': '',
        '/vmf/m8/detail': '',
        '/vmf/m8/modify': '',
        '/vmf/m8/delete': '',
        '/vmf/m8/index-get': '',
        '/vmf/m8/create-get': '',
        '/vmf/m8/detail-get': '',
        '/vmf/m8/modify-get': '',
        '/vmf/m8/delete-get': '',
        '/vmf/m8/index-post': '',
        '/vmf/m8/create-post': GroupCreateForm,
        '/vmf/m8/detail-post': '',
        '/vmf/m8/modify-post': '',
        '/vmf/m8/delete-post': '',

        '/vmf/m9/index': '',
        '/vmf/m9/create': '',
        '/vmf/m9/detail': '',
        '/vmf/m9/modify': '',
        '/vmf/m9/delete': '',
        '/vmf/m9/index-get': '',
        '/vmf/m9/create-get': '',
        '/vmf/m9/detail-get': '',
        '/vmf/m9/modify-get': '',
        '/vmf/m9/delete-get': '',
        '/vmf/m9/index-post': '',
        '/vmf/m9/create-post': GroupCreateForm,
        '/vmf/m9/detail-post': '',
        '/vmf/m9/modify-post': '',
        '/vmf/m9/delete-post': '',
        }
